config/routes.rb
LittleWorld::Application.routes.draw do

  resources :friends do
    get 'search', :on => :collection
  end
  
  root to: 'friends#index'
  
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :name
  
  validates :name, :latitude, :longitude, :presence => true

  validates :latitude,
            :numericality => true,
            :uniqueness => { :scope => :longitude }

  validates :longitude,
            :numericality => true,
            :uniqueness => { :scope => :latitude }
  
  def self.search( latitude = nil, longitude = nil )
    
    if latitude.nil? & longitude.nil?
      return all
    end
    
    friends = []
    
    friends = where( 'latitude = ?', latitude.to_i )   unless latitude.to_s.empty?
    friends = where( 'longitude = ?', longitude.to_i ) unless longitude.to_s.empty?
    friends = where( 'latitude = ? and longitude = ?', latitude.to_i, longitude.to_i ) unless latitude.to_s.empty? | longitude.to_s.empty?
    
    friends = near_to( friends.first ) unless friends.empty?
    
    friends.limit(4)
  end
  
  private
  
  def self.near_to( friend )
    radius = Math.exp(Math.cos(friend.latitude))
    
    select(:id)
    .select(:name)
    .select(:latitude)
    .select(:longitude)
    .select(:created_at)
    .select("((#{friend.latitude} - latitude) * (#{friend.latitude} - latitude) + (#{friend.longitude} - longitude) * (#{friend.longitude} - longitude) * #{radius})  as distance")
    .order("distance")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.search( params[:latitude], params[:longitude] )    
    params[:latitude], params[:longitude] = nil, nil

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friends }
    end
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
    @friend = Friend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/new
  # GET /friends/new.json
  def new
    @friend = Friend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(params[:friend])

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render json: @friend, status: :created, location: @friend }
      else
        format.html { render action: "new" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.json
  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def main_menu
    links = []
    
    options = params[:controller] == "friends" ? { class: "active" } : {}
    links << content_tag(:li, link_to("Friends", friends_path), options).html_safe
    
    content_tag(:ul, links.join("\n").html_safe, class: "nav")
  end
  
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= simple_form_for @friend, :wrapper => :inline, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), friends_path, :class => 'btn danger' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/friends/index.html.erb
<%- model_class = Friend -%>

<% content_for :subtitle do %>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<% end %>

<%= render 'shared/search' %>

<table id="friends">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= link_to friend.id, friend_path(friend) %></td>
        <td><%= friend.name %></td>
        <td><%= friend.latitude %></td>
        <td><%= friend.longitude %></td>
        <td><%=l friend.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_friend_path(friend), :class => 'btn primary' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      friend_path(friend),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_friend_path,
            :class => 'btn primary' %>

app/views/friends/new.html.erb
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/friends/show.html.erb
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @friend.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @friend.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @friend.longitude %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              friends_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_friend_path(@friend), :class => 'btn primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              friend_path(@friend),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title><%= "Little World" %></title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="master">
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <%= link_to "Little World", root_path, :class => 'brand' %>
          <div class="nav-collapse">
	        <%= main_menu %>
	      </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <% if notice %>
      <div class="alert-message success fade in" data-alert="alert">
        <a class="close" href="#">×</a>
        <p><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert-message alert fade in" data-alert="alert">
        <a class="close" href="#">×</a>
        <p><%= alert %></p>
      </div>
    <% end %>
	
    <div class="row">
      <div class="span16">
        <%= yield :subtitle %>
      </div>
      <div class="span15">
        <%= yield %>
      </div>
    </div>
  </div>

  <%= javascript_include_tag "application" %> 
  <%= yield :javascript %>
</body>
</html>

app/views/shared/_search.html.erb
<%= form_tag friends_path, :method => 'get' do %>  
  <p>  
    <%= text_field_tag :latitude, params[:latitude], :placeholder => 'latitude' %>  
    <%= text_field_tag :longitude, params[:longitude], :placeholder => 'longitude' %>  
    <%= submit_tag "Search", :name => nil, :class => 'btn' %>  
  </p>  
<% end %>